### ISSUE TITLE
PROJECT LAUNCHING PAD

### ISSUE THREAD

**Issue by procarrera** [cajlonbatista/novacrypt#1]
## Principais Funcionalidades:
- [ ] Desenvolver páginas de Criação
- - [ ] Criar Projeto
- - [ ] Submeter projetos para votação
- - [ ] Alocar membros
- - [ ] Decolar
- [ ] Desenvolver página de Acompanhamento

##### TASK: Criação do Projeto:
- [ ] Sistema de Cadastro e Login dos membros
- [ ] Página para criação de um Projeto
- [ ] Submeter projetos para votação

##### TASK: Projeto enviado para votação:
- [ ] Status do processo de cada projeto avança conforme o projeto tenha ao menos 50% de votos:
- - [ ] Create
- - [ ] Voting
- - [ ] Ready (above 50% up-votes)
- - [ ] Call for Crew
- - [ ] Fly !

##### TASK: Projetos aprovados:
- [ ] Membros podem se candidatar para as funções pré estabelecidas nas Roles
- [ ] Dono do projeto aceita as posições ou rejeita
- [ ] Status segue para Fly quando a crew estiver definida

##### TASK: Projetos reprovados:
- [ ] Ficam armazenados sujeitos a re-votação algum dia.
- [x] Nenhuma ideia é genuinamente ruim, apenas são suscetíveis ao contexto que as circundam

##### TASK: Acompanhamento:
- [ ] Página com listagem de todos os projetos classificados por status: em votação, aguardando definição de crew, em andamento, encerrados
